name: build_noble
on:
  pull_request:
  push:
    branches: [ rolling ]
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ['ubuntu:noble-20240225']
    container:
      image: ${{ matrix.docker_image }}
    timeout-minutes: 30
    steps:
    - name: Setup rolling
      run: |
        apt update && apt install curl -y
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
        apt update && apt install ros-dev-tools -y
        apt install ros-rolling-ros-base -y
    - uses: actions/checkout@v2
    - name: rosdep
      run: |
        rosdep init
        rosdep update
        rosdep install --from-paths . --rosdistro rolling -yir
    - name: build
      run: |
        source /opt/ros/rolling/setup.bash
        colcon build
